using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Aprillz.MewUI.Generators;

/// <summary>
/// Rewrites dotted binding lambdas into explicit BindingPath segment chains.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BindingPathGenerator : IIncrementalGenerator
{
    private const string MARKER_HINT_NAME = "BindingPathGeneratorMarker.g.cs";
    private const string ATTRIBUTE_HINT_NAME = "InterceptsLocationAttribute.g.cs";
    private const string INTERCEPTOR_HINT_NAME = "BindingPathInterceptors.g.cs";

    // MewUI.Analyzers probes this type to tell whether this generator ran in the compilation, so
    // the fully qualified name is a contract between the two assemblies.
    private const string MARKER_SOURCE = """
        // <auto-generated/>
        namespace Aprillz.MewUI.Generated
        {
            internal static class BindingPathGeneratorMarker
            {
            }
        }
        """;

    private const string ATTRIBUTE_SOURCE = """
        // <auto-generated/>
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
            internal sealed class InterceptsLocationAttribute : global::System.Attribute
            {
                public InterceptsLocationAttribute(int version, string data)
                {
                }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(postInitialization =>
        {
            postInitialization.AddSource(MARKER_HINT_NAME, MARKER_SOURCE);
            postInitialization.AddSource(ATTRIBUTE_HINT_NAME, ATTRIBUTE_SOURCE);
        });

        var calls = context.SyntaxProvider
            .CreateSyntaxProvider(IsCandidate, Transform)
            .Where(static call => call != null)
            .Collect();

        context.RegisterSourceOutput(calls, Emit!);
    }

    private static bool IsCandidate(SyntaxNode node, CancellationToken cancellationToken)
        => node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax
            {
                Name: IdentifierNameSyntax { Identifier.ValueText: "Bind" or "SetBinding" },
            },
        };

    private static BindingCall? Transform(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol
            is not IMethodSymbol method)
        {
            return null;
        }

        var owner = method.ContainingType;
        bool isExtension = method.Name == "Bind";
        if (isExtension
            ? owner.ToDisplayString() != "Aprillz.MewUI.Controls.BindingExtensions"
            : owner.ToDisplayString() != "Aprillz.MewUI.Controls.MewObject")
        {
            return null;
        }

        var parameters = method.ReducedFrom?.Parameters ?? method.Parameters;
        int getterIndex = IndexOfParameter(parameters, "getter");
        if (getterIndex < 0)
        {
            return null;
        }

        var arguments = invocation.ArgumentList.Arguments;
        if (FindArgument(arguments, parameters, "setter", isExtension) != null)
        {
            return null;
        }

        if (FindArgument(arguments, parameters, "getter", isExtension)
            is not AnonymousFunctionExpressionSyntax getter)
        {
            return null;
        }

        var chain = BindingChain.TryReadMemberChain(getter);
        if (chain == null || chain.Count < 2)
        {
            return null;
        }

        var segments = BindingChain.TryResolveSegments(
            context.SemanticModel.Compilation, context.SemanticModel, chain);
        if (segments == null)
        {
            return null;
        }

        var location = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (location == null)
        {
            return null;
        }

        var typeArguments = method.ReducedFrom?.TypeArguments ?? method.TypeArguments;
        bool hasConvert = IndexOfParameter(parameters, "convert") >= 0;

        string? receiverType = null;
        if (isExtension)
        {
            var receiver = ((MemberAccessExpressionSyntax)invocation.Expression).Expression;
            var receiverSymbol = context.SemanticModel.GetTypeInfo(receiver, cancellationToken).Type;
            if (receiverSymbol == null)
            {
                return null;
            }

            receiverType = Display(receiverSymbol);
        }
        else
        {
            var receiver = ((MemberAccessExpressionSyntax)invocation.Expression).Expression;
            var receiverSymbol = context.SemanticModel.GetTypeInfo(receiver, cancellationToken).Type;
            receiverType = receiverSymbol == null
                ? "global::Aprillz.MewUI.Controls.MewObject"
                : Display(receiverSymbol);
        }

        var sourceType = parameters[IndexOfParameter(parameters, "source")].Type;
        var getterDelegate = (INamedTypeSymbol)parameters[getterIndex].Type;
        var propertyType = (INamedTypeSymbol)parameters[IndexOfParameter(parameters, "property")].Type;

        return new BindingCall(
            location.Version,
            location.Data,
            isExtension,
            hasConvert,
            receiverType!,
            Display(Substitute(sourceType, method)),
            Display(Substitute(propertyType.TypeArguments[0], method)),
            Display(Substitute(getterDelegate.TypeArguments[1], method)),
            segments);
    }

    private static ITypeSymbol Substitute(ITypeSymbol type, IMethodSymbol method)
    {
        if (type is not ITypeParameterSymbol parameter || method.ReducedFrom == null)
        {
            return type;
        }

        var definition = method.ReducedFrom;
        for (int index = 0; index < definition.TypeParameters.Length; index++)
        {
            if (SymbolEqualityComparer.Default.Equals(definition.TypeParameters[index], parameter))
            {
                return method.TypeArguments[index];
            }
        }

        return type;
    }

    private static int IndexOfParameter(ImmutableArray<IParameterSymbol> parameters, string name)
    {
        for (int index = 0; index < parameters.Length; index++)
        {
            if (parameters[index].Name == name)
            {
                return index;
            }
        }

        return -1;
    }

    private static ExpressionSyntax? FindArgument(
        SeparatedSyntaxList<ArgumentSyntax> arguments,
        ImmutableArray<IParameterSymbol> parameters,
        string name,
        bool isExtension)
    {
        // A reduced extension call drops the receiver, so positional indexes shift by one.
        int target = IndexOfParameter(parameters, name) - (isExtension ? 1 : 0);
        for (int index = 0; index < arguments.Count; index++)
        {
            var argument = arguments[index];
            if (argument.NameColon is NameColonSyntax named)
            {
                if (named.Name.Identifier.ValueText == name)
                {
                    return argument.Expression;
                }
            }
            else if (index == target)
            {
                return argument.Expression;
            }
        }

        return null;
    }

    private static string Display(ITypeSymbol type)
        => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated)
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static void Emit(SourceProductionContext context, ImmutableArray<BindingCall?> calls)
    {
        var resolved = calls.Where(static call => call != null).Select(static call => call!).ToList();
        if (resolved.Count == 0)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Aprillz.MewUI.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class BindingPathInterceptors");
        builder.AppendLine("    {");

        for (int index = 0; index < resolved.Count; index++)
        {
            AppendCall(builder, resolved[index], index);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource(INTERCEPTOR_HINT_NAME, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void AppendCall(StringBuilder builder, BindingCall call, int index)
    {
        string path = $"_path{index}";
        builder.AppendLine(
            $"        private static readonly global::Aprillz.MewUI.BindingPath<{call.SourceType}, {call.ValueType}> {path} =");
        builder.AppendLine(
            $"            global::Aprillz.MewUI.BindingPath.From<{call.SourceType}>()");
        for (int segment = 0; segment < call.Segments.Count; segment++)
        {
            builder.AppendLine(
                "                " + FormatSegment(call.Segments[segment], segment == call.Segments.Count - 1)
                    + (segment == call.Segments.Count - 1 ? ";" : string.Empty));
        }

        builder.AppendLine();
        builder.AppendLine(
            $"        [global::System.Runtime.CompilerServices.InterceptsLocation({call.Version}, \"{call.Data}\")]");

        string returnType = call.IsExtension ? call.ReceiverType : "void";
        string name = call.IsExtension ? $"Bind{index}" : $"SetBinding{index}";
        builder.AppendLine($"        internal static {returnType} {name}(");
        builder.AppendLine($"            this {call.ReceiverType} target,");
        builder.AppendLine($"            global::Aprillz.MewUI.MewProperty<{call.PropertyType}> property,");
        builder.AppendLine($"            {call.SourceType} source,");
        builder.AppendLine(
            $"            global::System.Func<{call.SourceType}, {call.ValueType}> getter,");
        if (call.HasConvert)
        {
            builder.AppendLine(
                $"            global::System.Func<{call.ValueType}, {call.PropertyType}> convert,");
        }

        builder.AppendLine(
            $"            global::System.Action<{call.SourceType}, {call.ValueType}>? setter = null,");
        if (call.HasConvert)
        {
            builder.AppendLine(
                $"            global::System.Func<{call.PropertyType}, {call.ValueType}>? convertBack = null,");
        }

        builder.AppendLine("            global::Aprillz.MewUI.BindingMode? mode = null,");
        builder.AppendLine("            string? getterExpression = null)");
        builder.AppendLine("        {");
        builder.AppendLine(call.HasConvert
            ? $"            target.SetBinding(property, source, {path}, convert, convertBack, mode, default!);"
            : $"            target.SetBinding(property, source, {path}, mode, default!);");
        if (call.IsExtension)
        {
            builder.AppendLine("            return target;");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static string FormatSegment(BindingSegment segment, bool isLeaf)
    {
        string suppression = isLeaf ? string.Empty : "!";
        return segment.Kind switch
        {
            BindingSegmentKind.MewProperty
                => $".Then({segment.MewPropertyOwner}.{segment.MemberName}Property)",
            BindingSegmentKind.Notifying when isLeaf && segment.CanSetMember
                => $".ThenNotifying(static value => value.{segment.MemberName}, "
                    + $"static (value, newValue) => value.{segment.MemberName} = newValue)",
            BindingSegmentKind.Notifying
                => $".ThenNotifying(static value => value.{segment.MemberName}{suppression})",
            _ => $".Then(static value => value.{segment.MemberName}{suppression})",
        };
    }

    private sealed class BindingCall(
        int version,
        string data,
        bool isExtension,
        bool hasConvert,
        string receiverType,
        string sourceType,
        string propertyType,
        string valueType,
        List<BindingSegment> segments)
    {
        public int Version => version;

        public string Data => data;

        public bool IsExtension => isExtension;

        public bool HasConvert => hasConvert;

        public string ReceiverType => receiverType;

        public string SourceType => sourceType;

        public string PropertyType => propertyType;

        public string ValueType => valueType;

        public List<BindingSegment> Segments => segments;
    }
}
