using Microsoft.CodeAnalysis;

namespace Aprillz.MewUI.Generators;

/// <summary>
/// Rewrites dotted binding lambdas into explicit BindingPath segment chains.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BindingPathGenerator : IIncrementalGenerator
{
    private const string MARKER_HINT_NAME = "BindingPathGeneratorMarker.g.cs";

    // MewUI.Analyzers probes this type to tell whether this generator ran in the compilation, so
    // the fully qualified name is a contract between the two assemblies.
    private const string MARKER_SOURCE = """
        // <auto-generated/>
        namespace Aprillz.MewUI.Generated
        {
            internal static class BindingPathGeneratorMarker
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterPostInitializationOutput(
            postInitialization => postInitialization.AddSource(MARKER_HINT_NAME, MARKER_SOURCE));
}
